version: '3.9'

services:
  cardano-jobs:
    image: cardano-jobs-${NETWORK_NAME}
    restart: always
    build:
      context: .
      args:
        - PRIVATE_MVN_REGISTRY_URL=${PRIVATE_MVN_REGISTRY_URL}
        - PRIVATE_MVN_REGISTRY_USER=${PRIVATE_MVN_REGISTRY_USER}
        - PRIVATE_MVN_REGISTRY_PASS=${PRIVATE_MVN_REGISTRY_PASS}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=${SERVER_PORT}

      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - MAXIMUM_POOL_SIZE=${MAXIMUM_POOL_SIZE}
      - META_DATA_JOB_ENABLED=${META_DATA_JOB_ENABLED}
      - REPORT_HISTORY_JOB_ENABLED=${REPORT_HISTORY_JOB_ENABLED}
      - SET_EXPIRED_REPORTS_DELAY=${SET_EXPIRED_REPORTS_DELAY}
      - LIMIT_CONTENT_PER_SHEET=${LIMIT_CONTENT_PER_SHEET}
      - TOKEN_METADATA_URL=${TOKEN_METADATA_URL}
      - TOKEN_METADATA_FOLDER=${TOKEN_METADATA_FOLDER}
      - NETWORK_NAME=${NETWORK_NAME}

      - REPORT_S3_ACCESS_KEY=${REPORT_S3_ACCESS_KEY}
      - REPORT_S3_SECRET_KEY=${REPORT_S3_SECRET_KEY}
      - REPORT_S3_REGION=${REPORT_S3_REGION}
      - REPORT_S3_BUCKET_NAME=${REPORT_S3_BUCKET_NAME}
      - REPORT_S3_STORAGE_ENDPOINT=${REPORT_S3_STORAGE_ENDPOINT}

      - TOKEN_LOGO_S3_ACCESS_KEY=${TOKEN_LOGO_S3_ACCESS_KEY}
      - TOKEN_LOGO_S3_SECRET_KEY=${TOKEN_LOGO_S3_SECRET_KEY}
      - TOKEN_LOGO_S3_REGION=${TOKEN_LOGO_S3_REGION}
      - TOKEN_LOGO_S3_BUCKET_NAME=${TOKEN_LOGO_S3_BUCKET_NAME}
      - TOKEN_LOGO_S3_STORAGE_ENDPOINT=${TOKEN_LOGO_S3_STORAGE_ENDPOINT}

      - API_CHECK_REWARD_URL=${API_CHECK_REWARD_URL}
      - API_CHECK_POOL_HISTORY_URL=${API_CHECK_POOL_HISTORY_URL}
      - REDIS_SENTINEL_MASTER_NAME=${REDIS_SENTINEL_MASTER_NAME}
      - REDIS_SENTINEL_PASSWORD=${REDIS_SENTINEL_PASSWORD}
      - REDIS_SENTINEL_HOST=${REDIS_SENTINEL_HOST}
      - REDIS_SENTINEL_PORT=${REDIS_SENTINEL_PORT}
      - POOL_STATUS_FIXED_DELAY=${POOL_STATUS_FIXED_DELAY}
      - NUMBER_DELEGATOR_FIXED_DELAY=${NUMBER_DELEGATOR_FIXED_DELAY}
      - UNIQUE_ACCOUNT_FIXED_DELAY=${UNIQUE_ACCOUNT_FIXED_DELAY}
      - UNIQUE_ACCOUNT_ENABLED=${UNIQUE_ACCOUNT_ENABLED}
      - STAKE_TX_BALANCE_JOB_ENABLED=${STAKE_TX_BALANCE_JOB_ENABLED}
      - STAKE_TX_BALANCE_FIXED_DELAY=${STAKE_TX_BALANCE_FIXED_DELAY}
      - AGGREGATE_POOL_INFO_FIXED_DELAY=${AGGREGATE_POOL_INFO_FIXED_DELAY}
      - TOKEN_INFO_JOB_ENABLED=${TOKEN_INFO_JOB_ENABLED}
      - TOKEN_INFO_FIXED_DELAY=${TOKEN_INFO_FIXED_DELAY}
      - SMART_CONTRACT_INFO_FIXED_DELAY=${SMART_CONTRACT_INFO_FIXED_DELAY}
      - REPORT_HISTORY_FIXED_DELAY=${REPORT_HISTORY_FIXED_DELAY}

      - LEDGER_SYNC_HOST=${LEDGER_SYNC_HOST}
      - LEDGER_SYNC_PORT=${LEDGER_SYNC_PORT}
      - LEDGER_SYNC_DB=${LEDGER_SYNC_DB}
      - LEDGER_SYNC_SCHEMA=${LEDGER_SYNC_SCHEMA}
      - LEDGER_SYNC_USER=${LEDGER_SYNC_USER}
      - LEDGER_SYNC_PASSWORD=${LEDGER_SYNC_PASSWORD}
      - LEDGER_SYNC_FLYWAY_ENABLE=${LEDGER_SYNC_FLYWAY_ENABLE}

      - LEDGER_SYNC_AGG_HOST=${LEDGER_SYNC_AGG_HOST}
      - LEDGER_SYNC_AGG_PORT=${LEDGER_SYNC_AGG_PORT}
      - LEDGER_SYNC_AGG_USER=${LEDGER_SYNC_AGG_USER}
      - LEDGER_SYNC_AGG_PASSWORD=${LEDGER_SYNC_AGG_PASSWORD}
      - LEDGER_SYNC_AGG_DB=${LEDGER_SYNC_AGG_DB}
      - LEDGER_SYNC_AGG_SCHEMA=${LEDGER_SYNC_AGG_SCHEMA}
      - LEDGER_SYNC_AGG_FLYWAY_ENABLE=${LEDGER_SYNC_AGG_FLYWAY_ENABLE}

      - EXPLORER_HOST=${EXPLORER_HOST}
      - EXPLORER_PORT=${EXPLORER_PORT}
      - EXPLORER_DB=${EXPLORER_DB}
      - EXPLORER_SCHEMA=${EXPLORER_SCHEMA}
      - EXPLORER_USER=${EXPLORER_USER}
      - EXPLORER_PASSWORD=${EXPLORER_PASSWORD}
      - EXPLORER_FLYWAY_ENABLE=${EXPLORER_FLYWAY_ENABLE}

      - NATIVE_SCRIPT_INFO_FIXED_DELAY=${NATIVE_SCRIPT_INFO_FIXED_DELAY}
      - DREP_INFO_JOB_ENABLED=${DREP_INFO_JOB_ENABLED}
      - DREP_INFO_FIXED_DELAY=${DREP_INFO_FIXED_DELAY}
      - GOVERNANCE_INFO_JOB_ENABLED=${GOVERNANCE_INFO_JOB_ENABLED}
      - GOVERNANCE_INFO_FIXED_DELAY=${GOVERNANCE_INFO_FIXED_DELAY}
      - AGG_ANALYTIC_FIXED_DELAY=${AGG_ANALYTIC_FIXED_DELAY}
      - AGG_ANALYTIC_JOB_ENABLED=${AGG_ANALYTIC_JOB_ENABLED}
      - AGG_ANALYTIC_NUMBER_OF_CONCURRENT_TASKS=${AGG_ANALYTIC_NUMBER_OF_CONCURRENT_TASKS}

      - LATEST_TOKEN_BALANCE_FIXED_DELAY=${LATEST_TOKEN_BALANCE_FIXED_DELAY}
      - BLOCK_STATISTICS_DAILY_URL=${BLOCK_STATISTICS_DAILY_URL}
      - BLOCK_STATISTICS_PER_EPOCH_URL=${BLOCK_STATISTICS_PER_EPOCH_URL}
      - BLOCK_STATISTICS_JOB_ENABLED=${BLOCK_STATISTICS_JOB_ENABLED}
      - GOV_ACTION_METADATA_JOB_ENABLED=${GOV_ACTION_METADATA_JOB_ENABLED}
      - GOV_ACTION_METADATA_FIXED_DELAY=${GOV_ACTION_METADATA_FIXED_DELAY}
      - GOV_ACTION_METADATA_RETRY_COUNT=${GOV_ACTION_METADATA_RETRY_COUNT}
      - TOKEN_INFO_NUM_SLOT_INTERVAL=${TOKEN_INFO_NUM_SLOT_INTERVAL}
      - ADDRESS_TX_COUNT_FIXED_DELAY=${ADDRESS_TX_COUNT_FIXED_DELAY}
      - ADDRESS_TX_COUNT_JOB_ENABLED=${ADDRESS_TX_COUNT_JOB_ENABLED}
      - ADDRESS_TX_COUNT_NUM_SLOT_INTERVAL=${ADDRESS_TX_COUNT_NUM_SLOT_INTERVAL}
      - STAKE_ADDRESS_TX_COUNT_FIXED_DELAY=${STAKE_ADDRESS_TX_COUNT_FIXED_DELAY}
      - STAKE_ADDRESS_TX_COUNT_JOB_ENABLED=${STAKE_ADDRESS_TX_COUNT_JOB_ENABLED}
      - STAKE_ADDRESS_TX_COUNT_NUM_SLOT_INTERVAL=${STAKE_ADDRESS_TX_COUNT_NUM_SLOT_INTERVAL}
      - IPFS_GATEWAY_BASE_URL=${IPFS_GATEWAY_BASE_URL}