version: '3.9'

services:
  cardano-jobs:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: cardano-jobs-${NETWORK_NAME}
    restart: always
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - HOST=${HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - BOOTSTRAP_SERVER=${BOOTSTRAP_SERVER}

      - CARDANO_CLI_DELAY=${CARDANO_CLI_DELAY}
      - CRAWL_POOL_DATA_DELAY=${CRAWL_POOL_DATA_DELAY}
      - INSERT_POOL_DATA_DELAY=${INSERT_POOL_DATA_DELAY}
      - NETWORK_MAGIC=${NETWORK_MAGIC}
      - MAGIC_PARAM=${MAGIC_PARAM}

      - EPOCH_STAKE_TOPIC=${EPOCH_STAKE_TOPIC}
      - EPOCH_PARAM=${EPOCH_PARAM}

      - REWARD=${REWARD}
      - DOCKER_HOST=${DOCKER_HOST}
      - IMAGE_ID=${IMAGE_ID}

      - NETWORK_NAME=${NETWORK_NAME}
      - DOCKER_CONTAINER_NAME=${DOCKER_CONTAINER_NAME}

      - REDIS_MASTER_NAME=${REDIS_MASTER_NAME}
      - REDIS_SENTINEL_PASS=${REDIS_SENTINEL_PASS}
      - REDIS_SENTINEL_HOST=${REDIS_SENTINEL_HOST}
