version: '3.9'

services:
  cardano-jobs:
    image: cardano-jobs-${NETWORK_NAME}
    restart: always
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - MAXIMUM_POOL_SIZE=${MAXIMUM_POOL_SIZE}
      - META_DATA_JOB_ENABLED=${META_DATA_JOB_ENABLED}
      - REPORT_HISTORY_JOB_ENABLED=${REPORT_HISTORY_JOB_ENABLED}
      - SET_EXPIRED_REPORTS_DELAY=${SET_EXPIRED_REPORTS_DELAY}
      - LIMIT_CONTENT_PER_SHEET=${LIMIT_CONTENT_PER_SHEET}
      - POOL_OFFLINE_DATA_JOB_ENABLED=${POOL_OFFLINE_DATA_JOB_ENABLED}
      - CRAWL_POOL_DATA_DELAY=${CRAWL_POOL_DATA_DELAY}
      - TOKEN_METADATA_URL=${TOKEN_METADATA_URL}
      - TOKEN_METADATA_FOLDER=${TOKEN_METADATA_FOLDER}
      - NETWORK_NAME=${NETWORK_NAME}
      - KAFKA_CONFIGURATION_ENABLED=${KAFKA_CONFIGURATION_ENABLED}
      - KAFKA_BOOSTRAP_SERVER_URL=${KAFKA_BOOSTRAP_SERVER_URL}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - KAFKA_REPORTS_TOPIC=${KAFKA_REPORTS_TOPIC}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_STORAGE_ENDPOINT=${S3_STORAGE_ENDPOINT}
      - API_CHECK_REWARD_URL=${API_CHECK_REWARD_URL}
      - API_CHECK_POOL_HISTORY_URL=${API_CHECK_POOL_HISTORY_URL}
      - REDIS_SENTINEL_MASTER_NAME=${REDIS_SENTINEL_MASTER_NAME}
      - REDIS_SENTINEL_PASSWORD=${REDIS_SENTINEL_PASSWORD}
      - REDIS_SENTINEL_HOST=${REDIS_SENTINEL_HOST}
      - REDIS_SENTINEL_PORT=${REDIS_SENTINEL_PORT}
      - TOP_DELEGATORS_FIXED_DELAY=${TOP_DELEGATORS_FIXED_DELAY}