package org.cardanofoundation.job.common.enumeration;

public enum RedisKey {
  REDIS_TOP_STAKE_DELEGATORS,
  POOL_ACTIVATE,
  POOL_INACTIVATE,
  TOTAL_POOL,
  TOTAL_DELEGATOR,
  REDIS_TOKEN_PAGE,
  POOLS_LIVE_DELEGATORS_COUNT,
  POOLS_BLOCK_LIFETIME_EPOCH_SNAPSHOT,
  POOLS_BLOCK_LIFETIME,
  POOL_IDS_INACTIVATE
}
