package org.cardanofoundation.job.common.enumeration;

public enum RedisKey {
  REDIS_TOP_STAKE_DELEGATORS,
  POOL_ACTIVATE,
  POOL_INACTIVATE,
  TOTAL_POOL,
  TOTAL_DELEGATOR,
  REDIS_TOKEN_PAGE,
  POOL_IDS_INACTIVATE,
  SC_TX_CHECKPOINT,
  NATIVE_SCRIPT_CHECKPOINT,
  AGGREGATED_CACHE,
  TOTAL_TOKEN_COUNT,
  TOKEN_TX_COUNT_CHECKPOINT,
}
