name: Create a new Release

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  RELEASES_BRANCH: main
  DEVELOPMENT_BRANCH: develop

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set target branch
        id: snapshot
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ .*chore.${{ env.RELEASES_BRANCH }}.*release.* ]]
          then
            echo "TARGET_BRANCH=${{ env.DEVELOPMENT_BRANCH }}" >> $GITHUB_OUTPUT
          else
            echo "TARGET_BRANCH=${{ env.RELEASES_BRANCH }}" >> $GITHUB_OUTPUT
          fi

      - name: 🚀 release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          release-as: 0.0.2
          default-branch: ${{ steps.snapshot.outputs.TARGET_BRANCH }}
